### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by jimmyshadow1** [BenSova/ProjectICNS#1]
It can't seem to find the SwiftUIX framework. I don't really use Xcode that much so forgive me if that's a dumb thing to not know how to fix.

**Comment by BenSova** [comment]
[SwiftUIX is here](https://github.com/SwiftUIX/SwiftUIX). I thought Xcode bundled it with the project since its a Swift Package, but I could be wrong.

**Comment by jimmyshadow1** [comment]
are you able to install this to your device through xcode? im able to get it to run on simulator, but installing it to my phone makes xcode say my phone is no longer connected when it is.

**Comment by BenSova** [comment]
Yes, I have. Xcode is a little bit finicky, so it takes a little bit of effort to get it to work sometimes.

**Comment by jimmyshadow1** [comment]
Interesting, I've never had it do that for any apps I've tested. It also froze my computer running it in the simulator.

**Comment by jimmyshadow1** [comment]
Alright I got it installed.
